name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # 👈 THIS is the important line
  
jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build binaries
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/cvc-linux cmd/cvc
          GOOS=darwin GOARCH=amd64 go build -o dist/cvc-darwin cmd/cvc
          GOOS=windows GOARCH=amd64 go build -o dist/cvc.exe cmd/cvc

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
